
# Setting PATH for Python 3.7
# The original version is saved in .bash_profile.pysave
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
alias python="python3"
alias sbcl="rlwrap sbcl"
alias ros="rlwrap ros"
export CMAKE_PREFIX_PATH=/usr/local/opt/qt5/
export QTDIR=/usr/local/Cellar/qt5/5.15.2
launchctl setenv QTDIR $QTDIR
export SSL_CERT_FILE="/usr/local/share/curl/ca-certs.crt"
export CAFile="/usr/local/share/curl/ca-certs.crt"
export BIBINPUTS="/Users/houliu/Documents/School Work/Resources"
alias calculator="mosh hliu@100.84.18.107"
export TERM="xterm-256color-italic"
export PS1='\[\e[0;33m\]\u\[\e[0m\]@\[\e[0;32m\]\h\[\e[0m\]:\[\e[0;34m\]\w\[\e[0m\]\$ '
export EDITOR="nvim"
# Start tmux 
alias tmux='tmux -2'
alias mux='tmuxinator'
export DISPLAY=:0
set -o vi
bindkey jj vi-cmd-mode
export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
alias compilemd.pdf=" pandoc -f markdown -t pdf --pdf-engine=xelatex --mathjax --template=~/.pandoc/templates/default.latex"
alias officevnclegacy="ssh -f -N -L 5999:127.0.0.1:5900 hliu@server.shabang.cf -p 31415; echo VNC Tunnel to server.shabang.cf Ready at Port 5999."
alias officesshlegacy="ssh hliu@server.shabang.cf -p 31415"
alias officemoshlegacy='mosh hliu@server.shabang.cf --client=/usr/local/bin/mosh-client --server=/usr/local/bin/mosh-server --ssh="ssh -p 31415"'

alias officevnc="ssh -f -N -L 5999:127.0.0.1:5900 hliu@100.80.226.43; echo VNC Tunnel to server.shabang.cf Ready at Port 5999."
alias officesshts="ssh hliu@100.80.226.43"
alias officemosh='mosh hliu@100.80.226.43 --client=/usr/local/bin/mosh-client --server=/usr/local/bin/mosh-server'
alias modapssh='ssh houjun@172.29.172.28 -p 8322'
export PATH=/usr/local/bin:$PATH
alias grmdead="git fetch -p && for branch in \`git branch -vv | grep ': gone]' | awk '{print \$1}'\`; do git branch -D \$branch; done"

export PATH="/usr/local/opt/llvm/bin:$PATH"

interesting () {
    pushd ~/Documents/Projects/interesting/public/
    git pull 2>/dev/null
    imageurl=$(cat /dev/urandom | base64 | tr -dc '0-9a-zA-Z' | head -c30)
    pushd ./images
    pasteimage "./$imageurl.png"
    popd
    echo "![Pasted image $(date +%d.%m.%y-%H:%M:%S)](./images/$imageurl.png)" | pbcopy
    nvim ./Interesting.md
    git add -A
    git commit -m "[CI] [automated] Interesting commit! $(date +%d.%m.%y-%H:%M:%S)"
    git pull 2>/dev/null
    git push 2>/dev/null
    popd
}

alias i="interesting"

imgurpaste () {
    pushd /var/tmp
    imageurl=$(cat /dev/urandom | base64 | tr -dc '0-9a-zA-Z' | head -c30)
    pasteimage "./$imageurl.png"
    oup=$(imgur.sh "./$imageurl.png")
    echo "$oup"
    popd
}

# <Toggl Shortcuts>
alias tstart="toggl start"
alias tstop="toggl stop"
alias tt="toggl continue"
alias ttt="toggl continue Transition"
alias ttb="toggl continue Biology"
alias ttm="toggl continue Mealtime"
alias tte="toggl continue Errands"
alias ttcs="toggl continue Commute\ to\ School"
alias ttch="toggl continue Commute\ to\ Home"
alias ttsr="toggl continue Running"
alias ttsw="toggl continue Swimming"
alias tnowd="toggl now -d"
alias tnowp="toggl now -o"
alias tnow="toggl now"
alias tlshead="toggl ls | head"
alias t='toggl continue "$(toggl -s ls -f description | tail -n +2 | fzf)"'
alias ts='toggl start -o "$(toggl -s projects ls -f name | tail -n +2 | fzf)" '
# </Toggl Shortcuts>

alias emacs='emacs -nw'

alias ybbsp="yabai -m config layout bsp"
alias ybflt="yabai -m config layout float"

alias grmutb="git branch -vv | grep ': gone]'|  grep -v "\*" | awk '{ print $1; }' | xargs git branch -d"
export PYSPARK_PYTHON="python3"

export PATH="/usr/local/opt/qt/bin:$PATH"

